config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'places#index'
  resources :places do
    resources :comments, only: :create
    resources :photos, only: :create
  end

  resources :users, only: :show
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :place
    after_create :send_comment_email
    
    RATINGS = {
        'ONE STAR': '1_STAR',    
        'TWO STARS': '2_STARS',   
        'THREE STARS': '3_STARS',   
        'FOUR STARS': '4_STARS',   
        'FIVE STARS': '5_STARS'
    }

def humanized_rating
    RATINGS.invert[self.rating]     
end

def send_comment_email
   NotificationMailer.comment_added(self).deliver_now
end

end

app/models/photo.rb
class Photo < ApplicationRecord
    belongs_to :user
    belongs_to :place
    mount_uploader :picture, PictureUploader
end

app/models/place.rb
class Place < ApplicationRecord
    belongs_to :user
    has_many   :comments
    has_many :photos
    geocoded_by :address                #can also be an IP address
    after_validation :geocode           #auto-fetch coordinates
    # reverse_geocoded_by :latitude       #reverse geocoding
    # after_validation :reverse_geocode   #auto-fetch address
    
    validates :name, :address, :description, presence: true
    validates :name, length: {minimum: 3} 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :places
  has_many :comments
  has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    def index
    end
    
    def new
    end

    def create
        @place = Place.find(params[:place_id])
        @place.comments.create(comment_params.merge(user: current_user))
        redirect_to place_path(@place)
    end

    def edit
    end

    def update
    end

    def destroy
    end

    private 
        def comment_params
            params.require(:comment).permit(:message, :rating)
        end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
    before_action :authenticate_user!
    def index
    end
    
    def new
    end

    def create
        @place = Place.find(params[:place_id])
        @place.photos.create(photo_params.merge(user: current_user))
        redirect_to place_path(@place)
    end

    def edit
    end

    def update
    end

    def destroy
    end

    private 
        def photo_params
            params.require(:photo).permit(:caption, :picture)
        end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create, :edit, :update]
    def index
        @places = Place.page(params[:page]).per(2)
    end

    def new
        @place = Place.new
    end
    
    def create
        @place = current_user.places.create(place_params)
        if @place.valid?
            redirect_to root_path
        else
            render :new, status: :unprocessable_entity
        end
    end
    
    def show
        @place = Place.find(params[:id])
        @comment = Comment.new
        @photo = Photo.new
    end
    
    def edit
        @place = Place.find(params[:id])
        if @place.user != current_user
            return render text:'Not Allowed', status: :forbidden 
        end
    end
    
    def update
        @place = Place.find(params[:id])
        if current_user != @place.user
            return render text: 'Not Allowed', status: :forbidden
        end
        @place.update_attributes(place_params)
        if @place.valid?
            redirect_to root_path
        else
            render :edit, status: :unprocessable_entity
        end
    end
    
    def destroy
       @place = Place.find(params[:id])
        if current_user != @place.user
            return render text:"Not Allowed", status: :forbidden
        end
        @place.destroy
        redirect_to root_path
    end
    private
        def place_params
            params.require(:place).permit(:name, :description, :address)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user=User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nomster</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Anton" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-light style="background-color: #e3f2fd">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to "Nomster", root_path, class: "navbar-brand" %>
      
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item">
            <%= link_to new_place_path, class: "nav-link" do %>
              <i class="fa fa-plus-circle"></i>
              New Place
            <% end %>
          </li>
        </ul>
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'My Profile', user_path(current_user), class:'nav-link' %>
              <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
          <% else %>
            <li class='nav-item'>
              <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class='nav-item'>
              <%= link_to 'Sign Up', new_user_registration_path, class:'nav-link' %>
            </li>
            
          <% end %>
        </ul>
      </div>
    </nav>
    
    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/places/edit.html.erb
<div class="booyah-box col-10 offset-1">
    <br />
    <h1>Edit Place</h1>
    <br />
    <%= simple_form_for @place do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :description %>
        <br />
        <%= f.submit 'Update', class:'btn btn-primary'%>
    <% end %>    
</div>

app/views/places/index.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <%= image_tag image_url("Koala.jpg"), class:'d-block img-fluid', alt:'First slide'%>
      <div class="carousel-caption d-none d-md-block">
        <h3>Heading3</h3>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag(image_path("Hydrangeas.jpg"), class:'d-block img-fluid', alt:'Second slide')%>
      <div class="carousel-caption d-none d-md-block">
        <h3>Heading3</h3>
      </div>
    </div>
    <div class="carousel-item">
     <%= image_tag(image_path("Koala.jpg"), class:'d-block img-fluid', alt:'Third slide')%>
      <div class="carousel-caption d-none d-md-block">
        <h3>Heading3</h3>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>


<% @places.each do |place| %>
<div class="booyah-box col-10 offset-1">
    <h1><%= link_to place.name, place_path(place) %></h1>
    <i><%= place.address %></i><br /><br />
    <p><%= place.description %></p><br />

    <% if place.user.present? %>
        <small><%= place.user.email %></small>
    <% end %>

  <div class="col-12 col-sm-6">
    
    <% if place.comments.present? %>
    <blockquote class="blockquote">
      <% if place.comments.last.humanized_rating.present? %>
        <b><%= place.comments.last.humanized_rating %></b>
      <% end %>
      <%= place.comments.last.message %>
      <small class="blockquote-footer"> <%= place.comments.last.user.email %> </small>
    </blockquote>
    <% end %>

    <% if place.photos.present? %>
      <div class="img">
        <%= image_tag place.photos.last.picture %>
      </div>
      <blockquote class="blockquote">
        <% if place.photos.last.present? %>
          <b><%= place.photos.last.caption %></b>
        <% end %>
      <small class="blockquote-footer"> <%= place.photos.last.user.email %> </small>
    <% end %>


  </div>
</div>
<% end %>      
<hr />
<%= paginate @places %>
<!--<%= page_entries_info @places %>-->

app/views/places/new.html.erb
<div class="booyah-box col-10 offset-1">
    <h1>Enter Your Place Details</h1>
    <%= simple_form_for @place do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :description %>
        <br />
        
        <%= f.submit 'Create', class: 'btn btn-primary' %>
    <% end %>
</div>

app/views/places/show.html.erb
<div class="booyah-box col-10 offset-1">
    <h1><%= @place.name %></h1>
    <i><%= @place.address %></i><br /><br />
    <p><%= @place.description %></p>
    
    <%if @place.latitude.present? && @place.longitude.present? %> 
        <script>
          function initMap() {
            var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};
            var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 13,
              center: myLatLng
            });
            var marker = new google.maps.Marker({
              position: myLatLng,
              map: map,
              title: '<%= @place.name%>'
            });
          }
        </script>
        <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAfDwbI4Uvu2qS2uPxhn_QG1VNFlBC6eDU&callback=initMap">
        </script>
        
        <div id="map"></div>
    <% end %>
    <br />  
    <div class="float-right">
        <% if current_user && current_user == @place.user %>
        
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModalPhotos">
              Add a Photo
            </button>

            <%= link_to "Edit", edit_place_path(@place), class:'btn btn-primary' %>
            <%= link_to "Destroy", place_path(@place), method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-primary" %>
        <% end %>
    </div>
    <br />
    
    <!-- Modal Comments-->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Enter Your Comment</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          
          <div class="clear">
            <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
              <div class="modal-body">
                <%= f.input :message%>
                <%= f.input :rating, as: :select, label: 'Rating', include_blank: :false,  collection: Comment::RATINGS%>
                <br />
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <!--<button type="button" class="btn btn-primary">Save changes</button>-->
                <%= f.submit 'Add a Comment', class:'btn btn-primary'%>
              </div>
            <% end %>
          </div>
          
        </div>
      </div>
    </div>   
    
    <!-- Modal Photos-->
    <div class="modal fade" id="myModalPhotos" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Upload Your Picture</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          
          <div class="clear">
            <%= simple_form_for @photo, url: place_photos_path(@place) do |f| %>
              <div class="modal-body">
                <%= f.input :caption%>
                <%= f.input :picture%>
                <br />
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <!--<button type="button" class="btn btn-primary">Save changes</button>-->
                <%= f.submit 'Add a Photo', class:'btn btn-primary'%>
              </div>
            <% end %>
          </div>
          
        </div>
      </div>
    </div>   
    
    
    
    <div class="clear"></div>
    <br />
    <br />
    
    <!-- List of Comments -->        
    <div class="row">
      <div class="col-10 offset-1">
        <h1 class="float-left">Comments</h1>
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary float-right btn-lg" data-toggle="modal" data-target="#myModal">
          Add a Comment
        </button>
        <!--<button type="button" class="btn btn-primary float-right btn-lg" data-toggle="modal" data-target="#myModalPhotos">-->
        <!--  Add a Photo-->
        <!--</button>-->
    
        <div class="clear"></div>

        <!-- List of Comments -->    
        <div class="row">
        <%  @place.comments.each do |comment| %>
          <div class="col-12 col-sm-6">
            <blockquote class="blockquote">
              <% if comment.humanized_rating.present? %>
                <b><%= comment.humanized_rating %></b>
              <% end %>
              <%= comment.message %>
              <small class="blockquote-footer"> <%= comment.user.email %> </small>
            </blockquote>
          </div>
        <% end %>
        </div>
        
        <!-- List of Photos -->    
        <div class="row">
        <%  @place.photos.each do |photo| %>
          <div class="col-12 col-sm-6">
            <div class="img">
              <%= image_tag photo.picture %>
            </div>
            <blockquote class="blockquote">
              <% if photo.caption.present? %>
                <b><%= photo.caption %></b>
              <% end %>
              <small class="blockquote-footer"> <%= photo.user.email %> </small>
            </blockquote>
          </div>
        <% end %>
        </div>
        
        
      </div>
    </div>
    
</div>

app/views/users/show.html.erb
<div class="booyah-box">
    
    <div class="clear">
        <div class="row">
            <div class="col-4">
                <%= image_tag 'user.png' %>
            </div>
            <div class="col-8">
                <br />
                <h2><%= @user.email%></h2>
                <h3>Member Since: <%= @user.created_at.strftime("%B %d, %Y")%></h3>
                <h4><%=@user.comments.count%> total comments</h4>
                <h4><%=@user.comments.where(rating: '5_stars').count %> total 5-star reviews</h4>
            </div>
       </div> 
   </div>
   <div class="clear"></div>
   
    <div class="clear">
        <h2 class="text-center">My Comments</h2>
        <br /><br />
        <div class="row">
            <% current_user.comments.each do |comment| %>
 
            <div class="col-12 col-sm-6">
                <h2 class="text-center"><%= link_to comment.place.name, place_path(comment.place)%></h2>
                     <blockquote class="blockquote">
                          <% if comment.humanized_rating.present? %>
                            <b><%= comment.humanized_rating %></b>
                          <% end %>
                          <%= comment.message %>
                          <small class="blockquote-footer"> <%= comment.user.email %> </small>
                    </blockquote>
            </div>
            <% end %>
        </div>
    </div>
    
    <div class="clear">
        <br /><br />
        <h2 class="text-center">My Places</h2>
        <br /><br />
        <div class="row">
            <% current_user.places.each do |place|%>
                <div class="booyah-box col-10 offset-1">
                    <h1><%= link_to place.name, place_path(place) %></h1>
                    <i><%= place.address %></i><br /><br />
                    <p><%= place.description %></p><br />
    
                    <% if place.user.present? %>
                        <small><%= place.user.email %></small>
                    <% end %>
    
                    <div class="col-12 col-sm-6">
                         <% if place.comments.present? %>
                            <blockquote class="blockquote">
                              <% if place.comments.last.humanized_rating.present? %>
                                <b><%= place.comments.last.humanized_rating %></b>
                              <% end %>
                              <%= place.comments.last.message %>
                              <small class="blockquote-footer"> <%= place.comments.last.user.email %> </small>
                          </blockquote>
                        <% end %>
                    </div>
                </div>
            <%end%>
        </div>
</div>